apiVersion: v2
name: dp-chart
description: Data Platform (API + PostgreSQL + LakeFS + Unity Catalog)
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: lakefs
    version: "1.*"
    repository: https://charts.lakefs.io
    condition: lakefs.enabled
